#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 Joyent, Inc.
# Copyright 2025 RackTop Systems, Inc.
#

CRYPTO		= pkcs kcf
COMMON_OBJS	= main.o
SHA2_OBJS	= data_sha2.o key_sha2.o

TESTROOT	= $(ROOT)/opt/crypto-tests/tests/hmac

hmac_sha256_OBJS = $(SHA2_OBJS)
hmac_sha384_OBJS = $(SHA2_OBJS)
hmac_sha512_OBJS = $(SHA2_OBJS)

include $(SRC)/test/crypto-tests/tests/Makefile.crypto
