#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Jason King
#

ARCH = i86pc
CLASS = arch
DTDFILE = topology.dtd.1

TOPOFILE = \
	SYS-5028D-TN4T-hc-topology.xml \
	SYS-5028D-TN4T-chassis-hc-topology.xml \
	SYS-5028D-TN4T-disk-hc-topology.xml \
	SYS-5028D-TN4T-slot-hc-topology.xml \
	SYS-5028D-TN4T-usb.usbtopo \

SRCDIR = ../SMCI,SYS-5028D-TN4T

PLATFORM = SYS-5028D-TN4T

include ../Makefile.map
